require:
  - rubocop-airbnb

Rails:
  Enabled: true
Semicolon:
  Enabled: false
LineLength:
  Max: 150
EnumHash:
  Enabled: false
MethodCallWithoutArgsParentheses: 
  Enabled: false
BelongsTo:
  Enabled: false
ShadowingOuterLocalVariable:
  Enabled: false
SpaceInsideHashLiteralBraces:
  Enabled: false
Present:
  Enabled: false
DotPosition:
  Enabled: false
RedundantReturn:
  Enabled: false
AlignArguments:
  Enabled: false
RedundantSelf:
  Enabled: false
AllCops:
  # 除外
  Exclude:
    - vendor/bundle/**/*
    - 'bin/**'
    - 'lib/**'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*' 
    - 'node_modules/**/*'
    - '.git/**/*'
    - 'spec/spec_helper.rb'
