default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: free_development


test:
  <<: *default
  database: free_test

production:
  <<: *default
  database: free_production